name: Build and Deploy the Cairo Urban News Website
on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [update-source]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Update submodule
        run: git submodule update --remote src/CairoUrbanNews
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: npm install
      - run: npm run split
      - run: cp -R ./src/CairoUrbanNews ./src/CairoUrbanNews-ar
      - run: cp ar_docs.json ./src/CairoUrbanNews-ar/articles/articles.json
      - run: cp en_docs.json ./src/CairoUrbanNews/articles/articles.json
      - run: cp ar_pages.json ./src/CairoUrbanNews-ar/articles/arabic/pages/pages.json
      - run: cp ar_pages.json ./src/CairoUrbanNews-ar/articles/ottoman/pages/pages.json
      - run: cp en_pages.json ./src/CairoUrbanNews/articles/arabic/pages/pages.json
      - run: cp en_pages.json ./src/CairoUrbanNews/articles/ottoman/pages/pages.json
      - name: Build
        run: npx --node-options='--max-old-space-size=15360' @11ty/eleventy
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          commit_message: "Deploy Cairo Urban News Website"