name: Build and Deploy the Cairo Urban News Website
on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [update-source]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - run: cp -R ./src/CairoUrbanNews ./src/CairoUrbanNews-ar
      - run: cp ar_docs.json ./src/CairoUrbanNews-ar/articles/articles.json
      - run: cp en_docs.json ./src/CairoUrbanNews/articles/articles.json
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Build
        run: |
          npm install
          npx @11ty/eleventy
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          commit_message: "Deploy Cairo Urban News Website"